autorun update

diff --git a/image/autorun b/image/autorun
--- a/image/autorun
+++ b/image/autorun
@@ -33,41 +33,41 @@ LOGFILE=/mnt/usbkey/log_$(date +%Y%m%d).txt
 
 function led_orange_pulse 
 {
-    killall led
-    $LED -l $ORANGE -p 000000 -d 700 &
+..killall led
+..$LED -l $ORANGE -p 000000 -d 700 &
 }
 
 function led_orange
 {
-    killall led
-    $LED -l $ORANGE
+..killall led
+..$LED -l $ORANGE
 }
 
 
 function led_red {
-    killall led
-    $LED -l $RED
+..killall led
+..$LED -l $RED
 }
 
 function led_violet_pulse {
-    killall led
-    $LED -l $VIOLET -p 000000 -d 700 &
+..killall led
+..$LED -l $VIOLET -p 000000 -d 700 &
 
 }
 
 function led_green {
-    killall led
-    $LED -l $GREEN
+..killall led
+..$LED -l $GREEN
 }
 
 
 function PLAY {
-	killall madplay
-	$MPLAY $USB_MP3/$1.mp3 $2
+  killall madplay
+  $MPLAY $USB_MP3/$1.mp3 $2
 }
 
 function LOG {
-    echo $(date +"%T : ") $1 >> $LOGFILE
+..echo $(date +"%T : ") $1 >> $LOGFILE
 }
 
 
@@ -91,11 +91,11 @@ if [ ! -e "/mnt/usbkey/rootfs.wizz.120719r2.img.gz" ]; then
 fi
 
 if [ ! -e "/mnt/usbkey/rootfs.wizz.120719r2.img.gz.md5" ]; then
-	echo "ERROR: Unable to find rootfs signature file"
-	LOG "ERROR: Unable to find rootfs signature file"
-	led_red
-	PLAY "error"
-	exit 1
+  echo "ERROR: Unable to find rootfs signature file"
+  LOG "ERROR: Unable to find rootfs signature file"
+  led_red
+  PLAY "error"
+  exit 1
 fi
 
 SIGN=$(md5sum /mnt/usbkey/rootfs.wizz.120719r2.img.gz | cut -d' ' -f1)
@@ -105,16 +105,16 @@ echo "Computed  MD5 :"$SIGN
 echo "Reference MD5 :"$REF
 
 if [ "$SIGN" == "$REF" ]; then
-	echo "Check : Success"
-	LOG "Check success"
-	echo "Start Flashing"
+  echo "Check : Success"
+  LOG "Check success"
+  echo "Start Flashing"
 else
-	echo "Check : Failed"
-	LOG "ERROR: check failed $SIGN - $REF"
-	echo "Flashing Aborted"
-	led_red
-	PLAY "error"
-	exit 1   
+  echo "Check : Failed"
+  LOG "ERROR: check failed $SIGN - $REF"
+  echo "Flashing Aborted"
+  led_red
+  PLAY "error"
+  exit 1
 fi
 
 led_orange
@@ -123,7 +123,7 @@ LOG "Installation"
 
 echo "Erasing Flash"
 LOG "Erasing Flash"
-/sbin/flash_eraseall /dev/mtd2 
+/sbin/flash_eraseall /dev/mtd2
 
 echo "Flashing new firmware"
 LOG "Flashing Firmware"
@@ -133,15 +133,15 @@ sleep 10
 
 # Configuration for HTTPD, out of rootfs
 if [ ! -f /usr/httpd.conf ]; then
-	LOG "Installing httpd.conf file"
-	cp /mnt/usbkey/conf/httpd.conf /usr/
-	chown root.root /usr/httpd.conf
+  LOG "Installing httpd.conf file"
+  cp /mnt/usbkey/conf/httpd.conf /usr/
+  chown root.root /usr/httpd.conf
 fi
 
 if [ ! -d /usr/www/ ]; then
-	LOG "Creating /usr/www/"
-	mkdir -p /usr/www/
-	echo "It Works !!!" > /usr/www/index.html
+  LOG "Creating /usr/www/"
+  mkdir -p /usr/www/
+  echo "It Works !!!" > /usr/www/index.html
   chown -R 51.51 /usr/www/
 fi
 
